
use_frameworks!
target 'LarsonApp' do
    
    pod 'SDWebImage/WebP'
    pod 'Firebase/Messaging'
    pod 'Google/SignIn'
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'JGProgressHUD'
end
